/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_eduardoguevara_progra2;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author edujg
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_regname = new javax.swing.JTextField();
        tf_reguser = new javax.swing.JTextField();
        tf_regcontra = new javax.swing.JTextField();
        tf_regedad = new javax.swing.JTextField();
        tf_regid = new javax.swing.JTextField();
        rb_madre = new javax.swing.JRadioButton();
        rb_padre = new javax.swing.JRadioButton();
        rb_hermano = new javax.swing.JRadioButton();
        rb_hermana = new javax.swing.JRadioButton();
        rb_esposo = new javax.swing.JRadioButton();
        rb_m = new javax.swing.JRadioButton();
        rb_f = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        rb_personal = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        tf_regestc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_regocu = new javax.swing.JTextField();
        tf_reghora = new javax.swing.JTextField();
        j_datet = new com.toedter.calendar.JDateChooser();
        tf_regsuel = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_regtrab = new javax.swing.JTextField();
        tf_regalt = new javax.swing.JTextField();
        tf_regpeso = new javax.swing.JTextField();
        Familia = new javax.swing.ButtonGroup();
        Sexo = new javax.swing.ButtonGroup();
        Acciones = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tp_mensaj = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        tp_list = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cb_list = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        tp_mod = new javax.swing.JPanel();
        tp_elim = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cb_elim = new javax.swing.JComboBox<>();
        tp_create = new javax.swing.JPanel();
        bt_color = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_descript = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tf_marca = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tf_tamaño = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tf_calidad = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cb_dueño = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        j_datelife = new com.toedter.calendar.JDateChooser();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        j_datefc = new com.toedter.calendar.JDateChooser();
        jTextField6 = new javax.swing.JTextField();
        tf_suela = new javax.swing.JTextField();
        tf_confort = new javax.swing.JTextField();
        tf_talla = new javax.swing.JTextField();
        tf_material = new javax.swing.JTextField();
        tf_pelab = new javax.swing.JTextField();
        rb_cocina = new javax.swing.JRadioButton();
        rb_sala = new javax.swing.JRadioButton();
        rb_habitacion = new javax.swing.JRadioButton();
        tf_instruc = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        rb_z = new javax.swing.JRadioButton();
        rb_r = new javax.swing.JRadioButton();
        rb_h = new javax.swing.JRadioButton();
        Crear = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Tipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tf_logname = new javax.swing.JTextField();
        tf_logcontra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_login = new javax.swing.JButton();
        bt_register = new javax.swing.JButton();

        Register.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre:");
        Register.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 40, -1, -1));

        jLabel4.setText("Usuario:");
        Register.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 72, 49, -1));

        jLabel5.setText("Contraseña:");
        Register.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 104, -1, -1));

        jLabel6.setText("Rol:");
        Register.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel7.setText("Edad:");
        Register.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel8.setText("ID:");
        Register.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel9.setText("Sexo:");
        Register.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));
        Register.getContentPane().add(tf_regname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 120, 30));
        Register.getContentPane().add(tf_reguser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, 30));
        Register.getContentPane().add(tf_regcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, 30));
        Register.getContentPane().add(tf_regedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 120, 30));
        Register.getContentPane().add(tf_regid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 120, 30));

        Familia.add(rb_madre);
        rb_madre.setText("Madre");
        rb_madre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_madreActionPerformed(evt);
            }
        });
        Register.getContentPane().add(rb_madre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        Familia.add(rb_padre);
        rb_padre.setText("Padre");
        Register.getContentPane().add(rb_padre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        Familia.add(rb_hermano);
        rb_hermano.setText("Hermano");
        Register.getContentPane().add(rb_hermano, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        Familia.add(rb_hermana);
        rb_hermana.setText("Hermana");
        Register.getContentPane().add(rb_hermana, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        Familia.add(rb_esposo);
        rb_esposo.setText("Esposo");
        Register.getContentPane().add(rb_esposo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        Sexo.add(rb_m);
        rb_m.setText("M");
        Register.getContentPane().add(rb_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        Sexo.add(rb_f);
        rb_f.setText("F");
        Register.getContentPane().add(rb_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jButton1.setText("Register");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Register.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        Familia.add(rb_personal);
        rb_personal.setText("Personal");
        Register.getContentPane().add(rb_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel10.setText("Estado Civil:");
        Register.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));
        Register.getContentPane().add(tf_regestc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("En caso de ser Personal:");
        Register.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 170, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("En caso de ser algun Familiar:");
        Register.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        jLabel13.setText("Ocupacion:");
        Register.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jLabel14.setText("Horario:");
        Register.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel15.setText("Desde cuando trabaja:");
        Register.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jLabel16.setText("Sueldo:");
        Register.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));
        Register.getContentPane().add(tf_regocu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 100, 20));
        Register.getContentPane().add(tf_reghora, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 90, 20));
        Register.getContentPane().add(j_datet, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));
        Register.getContentPane().add(tf_regsuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 100, 20));

        jLabel17.setText("Trabajo:");
        Register.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        jLabel18.setText("Altura:");
        Register.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        jLabel19.setText("Peso:");
        Register.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));
        Register.getContentPane().add(tf_regtrab, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 120, 30));
        Register.getContentPane().add(tf_regalt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 120, 30));
        Register.getContentPane().add(tf_regpeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 120, 30));

        tp_mensaj.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Enviar Mensajes");
        tp_mensaj.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 130, 30));

        jButton3.setText("Ver Mensajes");
        tp_mensaj.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 120, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Bienvenido a la Mensajería:");
        tp_mensaj.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, 30));

        jTabbedPane1.addTab("Mensajeria", tp_mensaj);

        tp_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Rol", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tp_list.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 480, 280));

        tp_list.add(cb_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 130, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Seleccione una persona:");
        tp_list.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 30));

        jTabbedPane1.addTab("Listar", tp_list);

        javax.swing.GroupLayout tp_modLayout = new javax.swing.GroupLayout(tp_mod);
        tp_mod.setLayout(tp_modLayout);
        tp_modLayout.setHorizontalGroup(
            tp_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );
        tp_modLayout.setVerticalGroup(
            tp_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modificar", tp_mod);

        tp_elim.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Seleccione la Persona a la que desea Eliminar:");
        tp_elim.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 52, 319, 34));

        jButton4.setText("Eliminar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        tp_elim.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        tp_elim.add(cb_elim, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 130, 30));

        jTabbedPane1.addTab("Eliminar", tp_elim);

        tp_create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colorMouseClicked(evt);
            }
        });
        tp_create.add(bt_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 59, 41));

        jLabel23.setText("Color:");
        tp_create.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel24.setText("Descripcion:");
        tp_create.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        tp_create.add(tf_descript, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 90, 20));

        jLabel25.setText("Marca:");
        tp_create.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        tp_create.add(tf_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 90, -1));

        jLabel26.setText("Tamaño:");
        tp_create.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        tp_create.add(tf_tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 70, -1));

        jLabel27.setText("Calidad:");
        tp_create.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        tp_create.add(tf_calidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 70, 20));

        jLabel28.setText("Precio:");
        tp_create.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
        tp_create.add(tf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 70, -1));

        jLabel29.setText("Dueño:");
        tp_create.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        cb_dueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_dueñoActionPerformed(evt);
            }
        });
        tp_create.add(cb_dueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 130, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("En caso de ser Zapatos:");
        tp_create.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 170, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("En caso de ser Ropa:");
        tp_create.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("En caso de ser articulo de hogar:");
        tp_create.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jLabel33.setText("Talla:");
        tp_create.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        jLabel34.setText("Tipo de Suela:");
        tp_create.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel35.setText("Confort:");
        tp_create.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel36.setText("Talla:");
        tp_create.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel37.setText("Material:");
        tp_create.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        jLabel38.setText("Pais de Elaboracion:");
        tp_create.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));
        tp_create.add(j_datelife, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        jLabel39.setText("Cuando acaba su Vida Util:");
        tp_create.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jLabel40.setText("Area de la casa:");
        tp_create.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jLabel41.setText("Instrucciones de armado:");
        tp_create.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, 20));

        jLabel42.setText("Fecha de Compra:");
        tp_create.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));
        tp_create.add(j_datefc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));
        tp_create.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 40, 30));
        tp_create.add(tf_suela, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 70, -1));
        tp_create.add(tf_confort, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 40, 30));
        tp_create.add(tf_talla, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 40, 30));
        tp_create.add(tf_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 80, 20));
        tp_create.add(tf_pelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 100, 30));

        buttonGroup1.add(rb_cocina);
        rb_cocina.setText("Cocina");
        tp_create.add(rb_cocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        buttonGroup1.add(rb_sala);
        rb_sala.setText("Sala");
        tp_create.add(rb_sala, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        buttonGroup1.add(rb_habitacion);
        rb_habitacion.setText("Habitacion");
        tp_create.add(rb_habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));
        tp_create.add(tf_instruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 110, -1));

        jLabel43.setText("Tipo:");
        tp_create.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        Tipo.add(rb_z);
        rb_z.setText("Zapatos");
        tp_create.add(rb_z, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        Tipo.add(rb_r);
        rb_r.setText("Ropa");
        tp_create.add(rb_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        Tipo.add(rb_h);
        rb_h.setText("Hogar");
        tp_create.add(rb_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        Crear.setText("Crear");
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });
        tp_create.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, -1, -1));

        jTabbedPane1.addTab("Crear Objetos", tp_create);

        javax.swing.GroupLayout AccionesLayout = new javax.swing.GroupLayout(Acciones.getContentPane());
        Acciones.getContentPane().setLayout(AccionesLayout);
        AccionesLayout.setHorizontalGroup(
            AccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        AccionesLayout.setVerticalGroup(
            AccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 26));
        getContentPane().add(tf_logname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 127, 30));
        getContentPane().add(tf_logcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 127, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 90, 30));

        bt_login.setText("Login");
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginMouseClicked(evt);
            }
        });
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        getContentPane().add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        bt_register.setText("Register");
        bt_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registerMouseClicked(evt);
            }
        });
        getContentPane().add(bt_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_madreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_madreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_madreActionPerformed

    private void bt_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registerMouseClicked
        // TODO add your handling code here:
        if (users.contains(Kim) == false) {
            Kim.setNombre("Kim Kardashan");
            Kim.setUser("Kim");
            Kim.setContra("admin");
            users.add(Kim);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_dueño.getModel();
            modelo.addElement(Kim);
            cb_dueño.setModel(modelo);
            DefaultComboBoxModel model = (DefaultComboBoxModel) cb_list.getModel();
            model.addElement(Kim);
            cb_list.setModel(model);
            DefaultComboBoxModel mode = (DefaultComboBoxModel) cb_elim.getModel();
            mode.addElement(Kim);
            cb_elim.setModel(mode);
        }
        this.setVisible(false);
        Register.pack();
        Register.setVisible(true);
        rb_personal.setSelected(true);
        rb_m.setSelected(true);
        j_datet.setDate(new Date());
    }//GEN-LAST:event_bt_registerMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (rb_madre.isSelected() || rb_padre.isSelected() || rb_hermano.isSelected() || rb_hermana.isSelected() || rb_esposo.isSelected()) {
            int cont = 0;
            for (int i = 0; i < users.size(); i++) {
                if (users.get(i) instanceof Familiares) {
                    cont++;
                }
            }
            if (cont == 8) {
                JOptionPane.showMessageDialog(this, "Ya estan creados todos los familiares");
            }
        }
        boolean val = false;
        if (rb_madre.isSelected()) {
            for (int i = 0; i < users.size(); i++) {
                if (users.get(i) instanceof Madre) {
                    JOptionPane.showMessageDialog(this, "La madre de Kim ya esta creada");
                    val = false;
                    break;
                } else {
                    val = true;
                }
            }
        } else if (rb_padre.isSelected()) {
            for (int i = 0; i < users.size(); i++) {
                if (users.get(i) instanceof Padre) {
                    JOptionPane.showMessageDialog(this, "El padre de Kim ya esta creado");
                    val = false;
                    break;
                } else {
                    val = true;
                }
            }
        } else if (rb_esposo.isSelected()) {
            for (int i = 0; i < users.size(); i++) {
                if (users.get(i) instanceof Esposo) {
                    JOptionPane.showMessageDialog(this, "El esposo de Kim ya esta creado");
                    val = false;
                    break;
                } else {
                    val = true;
                }
            }
        } else if (rb_hermano.isSelected()) {
            for (int i = 0; i < users.size(); i++) {
                if (users.get(i) instanceof Hermano) {
                    JOptionPane.showMessageDialog(this, "El hermano de Kim ya esta creado");
                    val = false;
                    break;
                } else {
                    val = true;
                }
            }
        } else if (rb_hermana.isSelected()) {
            int ha = 0;
            for (int i = 0; i < users.size(); i++) {
                if (users.get(i) instanceof Hermana) {
                    ha++;
                }
            }
            if (ha == 4) {
                JOptionPane.showMessageDialog(this, "Ya estan creadas todas las hermanas de Kim");
                val = false;
            } else {
                val = true;
            }
        }
        if (val == true) {
            String nombre = tf_regname.getText();
            boolean usertaken = false;
            String user = tf_reguser.getText();
            for (int i = 0; i < users.size(); i++) {
                if (tf_regname.getText().equals(users.get(i).getUser())) {
                    usertaken = true;
                    JOptionPane.showMessageDialog(this, "El usuario ya existe");
                    break;
                } else {
                    usertaken = false;
                }
            }
            if (usertaken == false) {
                int edad = Integer.parseInt(tf_regedad.getText());
                String contra = tf_regcontra.getText();
                int id = Integer.parseInt(tf_regid.getText());
                String sexo = "";
                if (rb_m.isSelected()) {
                    sexo = "M";
                } else {
                    sexo = "F";
                }
                String estadoc = tf_regestc.getText();
                String rol = "";
                if (rb_madre.isSelected()) {
                    rol = "Madre";
                    String trabajo = tf_regtrab.getText();
                    float altura = Float.parseFloat(tf_regalt.getText());
                    float peso = Float.parseFloat(tf_regpeso.getText());
                    users.add(new Madre(trabajo, altura, peso, nombre, edad, id, sexo, estadoc, user, contra, rol));
                } else if (rb_padre.isSelected()) {
                    rol = "Padre";
                    String trabajo = tf_regtrab.getText();
                    float altura = Float.parseFloat(tf_regalt.getText());
                    float peso = Float.parseFloat(tf_regpeso.getText());
                    users.add(new Padre(trabajo, altura, peso, nombre, edad, id, sexo, estadoc, user, contra, rol));
                } else if (rb_hermano.isSelected()) {
                    rol = "Hermano";
                    String trabajo = tf_regtrab.getText();
                    float altura = Float.parseFloat(tf_regalt.getText());
                    float peso = Float.parseFloat(tf_regpeso.getText());
                    users.add(new Hermano(trabajo, altura, peso, nombre, edad, id, sexo, estadoc, user, contra, rol));
                } else if (rb_hermana.isSelected()) {
                    rol = "Hermana";
                    String trabajo = tf_regtrab.getText();
                    float altura = Float.parseFloat(tf_regalt.getText());
                    float peso = Float.parseFloat(tf_regpeso.getText());
                    users.add(new Hermana(trabajo, altura, peso, nombre, edad, id, sexo, estadoc, user, contra, rol));
                } else if (rb_esposo.isSelected()) {
                    rol = "Esposo";
                    String trabajo = tf_regtrab.getText();
                    float altura = Float.parseFloat(tf_regalt.getText());
                    float peso = Float.parseFloat(tf_regpeso.getText());
                    users.add(new Esposo(trabajo, altura, peso, nombre, edad, id, sexo, estadoc, user, contra, rol));
                } else {
                    rol = "Personal";
                    String ocupacion = tf_regocu.getText();
                    String horario = tf_reghora.getText();
                    int tiempo = (int) (new Date().getTime() - j_datet.getDate().getTime() * 1000 * 60 * 60 * 24 / 7);
                    float sueldo = Float.parseFloat(tf_regsuel.getText());
                    users.add(new Personal(ocupacion, horario, tiempo, sueldo, nombre, edad, id, sexo, estadoc, user, contra, rol));
                }

            }
            Register.setVisible(false);
            this.setVisible(true);
        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void bt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseClicked
        // TODO add your handling code here:
        if (users.contains(Kim) == false) {
            Kim.setNombre("Kim Kardashan");
            Kim.setUser("Kim");
            Kim.setContra("admin");
            users.add(Kim);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_dueño.getModel();
            modelo.addElement(Kim);
            cb_dueño.setModel(modelo);
            DefaultComboBoxModel model = (DefaultComboBoxModel) cb_list.getModel();
            model.addElement(Kim);
            cb_list.setModel(model);
            DefaultComboBoxModel mode = (DefaultComboBoxModel) cb_elim.getModel();
            mode.addElement(Kim);
            cb_elim.setModel(mode);
        }
        String nombre = tf_logname.getText();
        String contra = tf_logcontra.getText();
        boolean x = false;
        for (int i = 0; i < users.size(); i++) {
            if (users.get(i).getUser().equals(nombre)) {
                if (users.get(i).getContra().equals(contra)) {
                    this.setVisible(false);
                    actual = users.get(i);
                    x = true;
                    this.setVisible(false);
                    Acciones.pack();
                    Acciones.setVisible(true);
                    rb_z.setSelected(true);
                    rb_cocina.setSelected(true);
                    actual = users.get(i);
                    DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_dueño.getModel();
                    for (int b = 1; b < users.size(); b++) {
                        modelo.addElement(users.get(i).getNombre());
                    }
                    cb_dueño.setModel(modelo);
                    DefaultComboBoxModel model = (DefaultComboBoxModel) cb_list.getModel();
                    for (int b = 1; b < users.size(); b++) {
                        model.addElement(users.get(i).getNombre());
                    }
                    cb_list.setModel(model);
                    DefaultComboBoxModel mode = (DefaultComboBoxModel) cb_elim.getModel();
                    for (int b = 1; b < users.size(); b++) {
                        mode.addElement(users.get(i).getNombre());
                    }
                    cb_elim.setModel(mode);

                    if (users.contains(Kim) == false) {
                        Kim.setNombre("Kim Kardashan");
                        Kim.setUser("Kim");
                        Kim.setContra("admin");
                        users.add(Kim);
                        DefaultComboBoxModel mod = (DefaultComboBoxModel) cb_dueño.getModel();
                        modelo.addElement(Kim);
                        cb_dueño.setModel(mod);
                        DefaultComboBoxModel mod1 = (DefaultComboBoxModel) cb_list.getModel();
                        model.addElement(Kim);
                        cb_list.setModel(mod1);
                        DefaultComboBoxModel mod2 = (DefaultComboBoxModel) cb_elim.getModel();
                        mode.addElement(Kim);
                        cb_elim.setModel(mod2);
                    }
                    if (actual.equals(Kim)) {

                    } else {
                        tp_elim.setEnabled(false);
                        tp_mod.setEnabled(false);
                        tp_create.setEnabled(false);
                    }
                }
            }
        }
        if (!x) {
            JOptionPane.showMessageDialog(this, "El usuario no existe");
        }
        tf_logname.setText("");
        tf_logcontra.setText("");
    }//GEN-LAST:event_bt_loginMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_dueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_dueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_dueñoActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        users.remove(cb_elim.getSelectedIndex());
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_dueño.getModel();
        modelo.removeAllElements();
        for (int i = 0; i < users.size(); i++) {
            modelo.addElement(users.get(i).getNombre());
        }
        cb_dueño.setModel(modelo);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_list.getModel();
        model.removeAllElements();
        for (int i = 0; i < users.size(); i++) {
            model.addElement(users.get(i).getNombre());
        }
        cb_list.setModel(model);
        DefaultComboBoxModel mode = (DefaultComboBoxModel) cb_elim.getModel();
        mode.removeAllElements();
        for (int i = 0; i < users.size(); i++) {
            mode.addElement(users.get(i).getNombre());
        }
        cb_elim.setModel(mode);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bt_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colorMouseClicked
        // TODO add your handling code here:
        bt_color.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_bt_colorMouseClicked

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
        // TODO add your handling code here:
        Color color = bt_color.getForeground();
        String descrip = tf_descript.getText();
        String marca = tf_marca.getText();
        int tam = Integer.parseInt(tf_tamaño.getText());
        int calidad = Integer.parseInt(tf_calidad.getText());
        float precio = Float.parseFloat(tf_precio.getText());
        Personas due = (Personas) cb_dueño.getSelectedItem();
        if (rb_z.isSelected()) {
            int talla = Integer.parseInt(jTextField6.getText());
            int confort = Integer.parseInt(tf_confort.getText());
            String suela = tf_suela.getText();
            ((Familiares) (due)).getPertenencias().add(new Zapatos(Integer.toString(talla), suela, confort, color, descrip, marca, tam, calidad, precio, due));

        } else if (rb_r.isSelected()) {
            int talla = Integer.parseInt(tf_talla.getText());
            String material = tf_material.getText();
            String paiselab = tf_pelab.getText();
            ((Familiares) (due)).getPertenencias().add(new Ropa(talla, material, paiselab, color, descrip, marca, tam, calidad, precio, due));

        } else {
            Date lifetime = j_datelife.getDate();
            Date fechac = j_datefc.getDate();
            String area = "";
            if (rb_cocina.isSelected()) {
                area = "Cocina";
            } else if (rb_sala.isSelected()) {
                area = "Sala";
            } else {
                area = "Habitacion";
            }
            String instruc = tf_instruc.getText();
            ((Familiares) (due)).getPertenencias().add(new ObjetosHogar(lifetime, area, instruc, fechac, color, descrip, marca, tam, calidad, precio, due));
        }
    }//GEN-LAST:event_CrearMouseClicked

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    ArrayList<Personas> users = new ArrayList();
    Personas actual;
    ArrayList<Mensajes> msgs;
    Familiares Kim = new Familiares();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Acciones;
    private javax.swing.JButton Crear;
    private javax.swing.ButtonGroup Familia;
    private javax.swing.JFrame Register;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.ButtonGroup Tipo;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_register;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_dueño;
    private javax.swing.JComboBox<String> cb_elim;
    private javax.swing.JComboBox<String> cb_list;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private com.toedter.calendar.JDateChooser j_datefc;
    private com.toedter.calendar.JDateChooser j_datelife;
    private com.toedter.calendar.JDateChooser j_datet;
    private javax.swing.JRadioButton rb_cocina;
    private javax.swing.JRadioButton rb_esposo;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_h;
    private javax.swing.JRadioButton rb_habitacion;
    private javax.swing.JRadioButton rb_hermana;
    private javax.swing.JRadioButton rb_hermano;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_madre;
    private javax.swing.JRadioButton rb_padre;
    private javax.swing.JRadioButton rb_personal;
    private javax.swing.JRadioButton rb_r;
    private javax.swing.JRadioButton rb_sala;
    private javax.swing.JRadioButton rb_z;
    private javax.swing.JTextField tf_calidad;
    private javax.swing.JTextField tf_confort;
    private javax.swing.JTextField tf_descript;
    private javax.swing.JTextField tf_instruc;
    private javax.swing.JTextField tf_logcontra;
    private javax.swing.JTextField tf_logname;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_material;
    private javax.swing.JTextField tf_pelab;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_regalt;
    private javax.swing.JTextField tf_regcontra;
    private javax.swing.JTextField tf_regedad;
    private javax.swing.JTextField tf_regestc;
    private javax.swing.JTextField tf_reghora;
    private javax.swing.JTextField tf_regid;
    private javax.swing.JTextField tf_regname;
    private javax.swing.JTextField tf_regocu;
    private javax.swing.JTextField tf_regpeso;
    private javax.swing.JTextField tf_regsuel;
    private javax.swing.JTextField tf_regtrab;
    private javax.swing.JTextField tf_reguser;
    private javax.swing.JTextField tf_suela;
    private javax.swing.JTextField tf_talla;
    private javax.swing.JTextField tf_tamaño;
    private javax.swing.JPanel tp_create;
    private javax.swing.JPanel tp_elim;
    private javax.swing.JPanel tp_list;
    private javax.swing.JPanel tp_mensaj;
    private javax.swing.JPanel tp_mod;
    // End of variables declaration//GEN-END:variables
}
