/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_eduardoguevara_progra2;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author edujg
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_contraa = new javax.swing.JTextField();
        tf_usern = new javax.swing.JTextField();
        tf_age = new javax.swing.JTextField();
        tf_ident = new javax.swing.JTextField();
        tf_sex = new javax.swing.JTextField();
        tf_ec = new javax.swing.JTextField();
        rb_madre = new javax.swing.JRadioButton();
        rb_padre = new javax.swing.JRadioButton();
        rb_hermano = new javax.swing.JRadioButton();
        rb_hermana = new javax.swing.JRadioButton();
        rb_esposo = new javax.swing.JRadioButton();
        rb_personal = new javax.swing.JRadioButton();
        Registrar2 = new javax.swing.JButton();
        Familia = new javax.swing.ButtonGroup();
        Sexo = new javax.swing.ButtonGroup();
        Acciones = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tp_mensaj = new javax.swing.JPanel();
        send = new javax.swing.JButton();
        see = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cb_mensaje = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        tp_list = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cb_list = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        tp_mod = new javax.swing.JPanel();
        tp_elim = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cb_elim = new javax.swing.JComboBox<>();
        tp_create = new javax.swing.JPanel();
        bt_color = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_descript = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tf_marca = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tf_tamaño = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tf_calidad = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cb_dueño = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        j_datelife = new com.toedter.calendar.JDateChooser();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        j_datefc = new com.toedter.calendar.JDateChooser();
        jTextField6 = new javax.swing.JTextField();
        tf_suela = new javax.swing.JTextField();
        tf_confort = new javax.swing.JTextField();
        tf_talla = new javax.swing.JTextField();
        tf_material = new javax.swing.JTextField();
        tf_pelab = new javax.swing.JTextField();
        rb_cocina = new javax.swing.JRadioButton();
        rb_sala = new javax.swing.JRadioButton();
        rb_habitacion = new javax.swing.JRadioButton();
        tf_instruc = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        rb_z = new javax.swing.JRadioButton();
        rb_r = new javax.swing.JRadioButton();
        rb_h = new javax.swing.JRadioButton();
        Crear = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Tipo = new javax.swing.ButtonGroup();
        Rol = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tf_logname = new javax.swing.JTextField();
        tf_logcontra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_login = new javax.swing.JButton();
        bt_register = new javax.swing.JButton();

        Register.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setText("Nombre:");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 66, -1, -1));

        jLabel45.setText("Contra:");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 107, -1, -1));

        jLabel46.setText("User:");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 149, -1, -1));
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 196, -1, -1));

        jLabel48.setText("Edad:");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel3.setText("ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel4.setText("Sexo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel5.setText("Estado Civil:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel6.setText("Rol:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));
        jPanel1.add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 100, 30));
        jPanel1.add(tf_contraa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 110, -1));
        jPanel1.add(tf_usern, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 120, -1));
        jPanel1.add(tf_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 120, 20));
        jPanel1.add(tf_ident, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 130, 20));
        jPanel1.add(tf_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 70, -1));
        jPanel1.add(tf_ec, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 70, 20));

        Rol.add(rb_madre);
        rb_madre.setText("Madre:");
        rb_madre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_madreActionPerformed(evt);
            }
        });
        jPanel1.add(rb_madre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        Rol.add(rb_padre);
        rb_padre.setText("Padre:");
        jPanel1.add(rb_padre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        Rol.add(rb_hermano);
        rb_hermano.setText("Hermano");
        jPanel1.add(rb_hermano, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        Rol.add(rb_hermana);
        rb_hermana.setText("Hermana");
        jPanel1.add(rb_hermana, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        Rol.add(rb_esposo);
        rb_esposo.setText("Esposo");
        jPanel1.add(rb_esposo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        Rol.add(rb_personal);
        rb_personal.setText("Personal");
        jPanel1.add(rb_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        Registrar2.setText("Registrar");
        Registrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Registrar2MouseClicked(evt);
            }
        });
        jPanel1.add(Registrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        Register.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 490));

        tp_mensaj.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        send.setText("Enviar Mensajes");
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });
        tp_mensaj.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 130, 30));

        see.setText("Ver Mensajes");
        see.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeMouseClicked(evt);
            }
        });
        tp_mensaj.add(see, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 120, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Bienvenido a la Mensajería:");
        tp_mensaj.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, 30));

        tp_mensaj.add(cb_mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, 30));

        jLabel7.setText("Mensaje a enviar:");
        tp_mensaj.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane2.setViewportView(ta_mensaje);

        tp_mensaj.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 220, 190));

        jTabbedPane1.addTab("Mensajeria", tp_mensaj);

        tp_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Rol", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tp_list.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 480, 280));

        tp_list.add(cb_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 130, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Seleccione una persona:");
        tp_list.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 30));

        jTabbedPane1.addTab("Listar", tp_list);

        javax.swing.GroupLayout tp_modLayout = new javax.swing.GroupLayout(tp_mod);
        tp_mod.setLayout(tp_modLayout);
        tp_modLayout.setHorizontalGroup(
            tp_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );
        tp_modLayout.setVerticalGroup(
            tp_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modificar", tp_mod);

        tp_elim.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Seleccione la Persona a la que desea Eliminar:");
        tp_elim.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 52, 319, 34));

        jButton4.setText("Eliminar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        tp_elim.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        tp_elim.add(cb_elim, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 130, 30));

        jTabbedPane1.addTab("Eliminar", tp_elim);

        tp_create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colorMouseClicked(evt);
            }
        });
        tp_create.add(bt_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 59, 41));

        jLabel23.setText("Color:");
        tp_create.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel24.setText("Descripcion:");
        tp_create.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        tp_create.add(tf_descript, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 90, 20));

        jLabel25.setText("Marca:");
        tp_create.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        tp_create.add(tf_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 90, -1));

        jLabel26.setText("Tamaño:");
        tp_create.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        tp_create.add(tf_tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 70, -1));

        jLabel27.setText("Calidad:");
        tp_create.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        tp_create.add(tf_calidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 70, 20));

        jLabel28.setText("Precio:");
        tp_create.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
        tp_create.add(tf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 70, -1));

        jLabel29.setText("Dueño:");
        tp_create.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        cb_dueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_dueñoActionPerformed(evt);
            }
        });
        tp_create.add(cb_dueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 130, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("En caso de ser Zapatos:");
        tp_create.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 170, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("En caso de ser Ropa:");
        tp_create.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("En caso de ser articulo de hogar:");
        tp_create.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jLabel33.setText("Talla:");
        tp_create.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        jLabel34.setText("Tipo de Suela:");
        tp_create.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel35.setText("Confort:");
        tp_create.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel36.setText("Talla:");
        tp_create.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel37.setText("Material:");
        tp_create.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        jLabel38.setText("Pais de Elaboracion:");
        tp_create.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));
        tp_create.add(j_datelife, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        jLabel39.setText("Cuando acaba su Vida Util:");
        tp_create.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jLabel40.setText("Area de la casa:");
        tp_create.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jLabel41.setText("Instrucciones de armado:");
        tp_create.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, 20));

        jLabel42.setText("Fecha de Compra:");
        tp_create.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));
        tp_create.add(j_datefc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));
        tp_create.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 40, 30));
        tp_create.add(tf_suela, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 70, -1));
        tp_create.add(tf_confort, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 40, 30));
        tp_create.add(tf_talla, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 40, 30));
        tp_create.add(tf_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 80, 20));
        tp_create.add(tf_pelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 100, 30));

        buttonGroup1.add(rb_cocina);
        rb_cocina.setText("Cocina");
        tp_create.add(rb_cocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        buttonGroup1.add(rb_sala);
        rb_sala.setText("Sala");
        tp_create.add(rb_sala, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        buttonGroup1.add(rb_habitacion);
        rb_habitacion.setText("Habitacion");
        tp_create.add(rb_habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));
        tp_create.add(tf_instruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 110, -1));

        jLabel43.setText("Tipo:");
        tp_create.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        Tipo.add(rb_z);
        rb_z.setText("Zapatos");
        tp_create.add(rb_z, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        Tipo.add(rb_r);
        rb_r.setText("Ropa");
        tp_create.add(rb_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        Tipo.add(rb_h);
        rb_h.setText("Hogar");
        tp_create.add(rb_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        Crear.setText("Crear");
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });
        tp_create.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, -1, -1));

        jTabbedPane1.addTab("Crear Objetos", tp_create);

        javax.swing.GroupLayout AccionesLayout = new javax.swing.GroupLayout(Acciones.getContentPane());
        Acciones.getContentPane().setLayout(AccionesLayout);
        AccionesLayout.setHorizontalGroup(
            AccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        AccionesLayout.setVerticalGroup(
            AccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 26));
        getContentPane().add(tf_logname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 127, 30));
        getContentPane().add(tf_logcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 127, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 90, 30));

        bt_login.setText("Login");
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginMouseClicked(evt);
            }
        });
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        getContentPane().add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        bt_register.setText("Register");
        bt_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registerMouseClicked(evt);
            }
        });
        getContentPane().add(bt_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registerMouseClicked
        // TODO add your handling code here:
        if (users.contains(Kim) == false) {
            Kim.setNombre("Kim Kardashan");
            Kim.setUser("Kim");
            Kim.setContra("admin");
            users.add(Kim);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_dueño.getModel();
            modelo.addElement(Kim);
            cb_dueño.setModel(modelo);
            DefaultComboBoxModel model = (DefaultComboBoxModel) cb_list.getModel();
            model.addElement(Kim);
            cb_list.setModel(model);
            DefaultComboBoxModel mode = (DefaultComboBoxModel) cb_elim.getModel();
            mode.addElement(Kim);
            cb_elim.setModel(mode);
        }
        this.setVisible(false);
        Register.pack();
        Register.setVisible(true);
        rb_personal.setSelected(true);
        //rb_m.setSelected(true);
        //j_datet.setDate(new Date());
    }//GEN-LAST:event_bt_registerMouseClicked

    private void bt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseClicked
        // TODO add your handling code here:
        if (users.contains(Kim) == false) {
            Kim.setNombre("Kim Kardashan");
            Kim.setUser("Kim");
            Kim.setContra("admin");
            users.add(Kim);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_dueño.getModel();
            modelo.addElement(Kim);
            cb_dueño.setModel(modelo);
            DefaultComboBoxModel model = (DefaultComboBoxModel) cb_list.getModel();
            model.addElement(Kim);
            cb_list.setModel(model);
            DefaultComboBoxModel mode = (DefaultComboBoxModel) cb_elim.getModel();
            mode.addElement(Kim);
            cb_elim.setModel(mode);
        }
        String nombre = tf_logname.getText();
        String contra = tf_logcontra.getText();
        boolean x = false;
        for (int i = 0; i < users.size(); i++) {
            if (users.get(i).getUser().equals(nombre)) {
                if (users.get(i).getContra().equals(contra)) {
                    this.setVisible(false);
                    actual = users.get(i);
                    x = true;
                    this.setVisible(false);
                    Acciones.pack();
                    Acciones.setVisible(true);
                    rb_z.setSelected(true);
                    rb_cocina.setSelected(true);
                    actual = users.get(i);
                    /*DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_dueño.getModel();
                    for (int b = 1; b < users.size(); b++) {
                        modelo.addElement(users.get(i).getNombre());
                    }
                    cb_dueño.setModel(modelo);
                    DefaultComboBoxModel model = (DefaultComboBoxModel) cb_list.getModel();
                    for (int b = 1; b < users.size(); b++) {
                        model.addElement(users.get(i).getNombre());
                    }
                    cb_list.setModel(model);
                    DefaultComboBoxModel mode = (DefaultComboBoxModel) cb_elim.getModel();
                    for (int b = 1; b < users.size(); b++) {
                        mode.addElement(users.get(i).getNombre());
                    }
                    cb_elim.setModel(mode);
                    */
                    if (users.contains(Kim) == false) {
                        Kim.setNombre("Kim Kardashan");
                        Kim.setUser("Kim");
                        Kim.setContra("admin");
                        users.add(Kim);
                        DefaultComboBoxModel mod = (DefaultComboBoxModel) cb_dueño.getModel();
                        modelo.addElement(Kim);
                        cb_dueño.setModel(mod);
                        DefaultComboBoxModel mod1 = (DefaultComboBoxModel) cb_list.getModel();
                        model.addElement(Kim);
                        cb_list.setModel(mod1);
                        DefaultComboBoxModel mod2 = (DefaultComboBoxModel) cb_elim.getModel();
                        mode.addElement(Kim);
                        cb_elim.setModel(mod2);
                        DefaultComboBoxModel c = (DefaultComboBoxModel) cb_mensaje.getModel();
                        c.addElement(Kim);
                        cb_mensaje.setModel(c);
                    }
                    if (actual.equals(Kim)) {
                        
                    } else {
                        tp_elim.setEnabled(false);
                        tp_mod.setEnabled(false);
                        tp_create.setEnabled(false);
                    }
                }
            }
        }
        if (!x) {
            JOptionPane.showMessageDialog(this, "El usuario no existe");
        }
        tf_logname.setText("");
        tf_logcontra.setText("");
    }//GEN-LAST:event_bt_loginMouseClicked

    private void cb_dueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_dueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_dueñoActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        users.remove(cb_elim.getSelectedIndex());
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_dueño.getModel();
        modelo.removeAllElements();
        for (int i = 0; i < users.size(); i++) {
            modelo.addElement(users.get(i).getNombre());
        }
        cb_dueño.setModel(modelo);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_list.getModel();
        model.removeAllElements();
        for (int i = 0; i < users.size(); i++) {
            model.addElement(users.get(i).getNombre());
        }
        cb_list.setModel(model);
        DefaultComboBoxModel mode = (DefaultComboBoxModel) cb_elim.getModel();
        mode.removeAllElements();
        for (int i = 0; i < users.size(); i++) {
            mode.addElement(users.get(i).getNombre());
        }
        cb_elim.setModel(mode);
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_mensaje.getModel();
        m.removeAllElements();
        for (int i = 0; i < users.size(); i++) {
            m.addElement(users.get(i).getNombre());
        }
        cb_mensaje.setModel(m);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bt_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colorMouseClicked
        // TODO add your handling code here:
        bt_color.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_bt_colorMouseClicked

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
        // TODO add your handling code here:
        Color color = bt_color.getBackground();
        String descrip = tf_descript.getText();
        String marca = tf_marca.getText();
        int tam = Integer.parseInt(tf_tamaño.getText());
        int calidad = Integer.parseInt(tf_calidad.getText());
        float precio = Float.parseFloat(tf_precio.getText());
        Personas due = (Personas) cb_dueño.getSelectedItem();
        if (rb_z.isSelected()) {
            int talla = Integer.parseInt(jTextField6.getText());
            int confort = Integer.parseInt(tf_confort.getText());
            String suela = tf_suela.getText();
            ((Familiares) (due)).getPertenencias().add(new Zapatos(Integer.toString(talla), suela, confort, color, descrip, marca, tam, calidad, precio, due));
            bt_color.setBackground(Color.red);
            tf_descript.setText("");
            tf_marca.setText("");
            tf_tamaño.setText("");
            tf_calidad.setText("");
            tf_precio.setText("");
            cb_dueño.setSelectedIndex(0);
            jTextField6.setText("");
            tf_confort.setText("");
            tf_suela.setText("");
            
        } else if (rb_r.isSelected()) {
            int talla = Integer.parseInt(tf_talla.getText());
            String material = tf_material.getText();
            String paiselab = tf_pelab.getText();
            ((Familiares) (due)).getPertenencias().add(new Ropa(talla, material, paiselab, color, descrip, marca, tam, calidad, precio, due));
            bt_color.setBackground(Color.red);
            tf_descript.setText("");
            tf_marca.setText("");
            tf_tamaño.setText("");
            tf_calidad.setText("");
            tf_precio.setText("");
            cb_dueño.setSelectedIndex(0);
            tf_talla.setText("");
            tf_material.setText("");
            tf_pelab.setText("");
        } else {
            Date lifetime = j_datelife.getDate();
            Date fechac = j_datefc.getDate();
            String area = "";
            if (rb_cocina.isSelected()) {
                area = "Cocina";
            } else if (rb_sala.isSelected()) {
                area = "Sala";
            } else {
                area = "Habitacion";
            }
            String instruc = tf_instruc.getText();
            ((Familiares) (due)).getPertenencias().add(new ObjetosHogar(lifetime, area, instruc, fechac, color, descrip, marca, tam, calidad, precio, due));
            bt_color.setBackground(Color.red);
            tf_descript.setText("");
            tf_marca.setText("");
            tf_tamaño.setText("");
            tf_calidad.setText("");
            tf_precio.setText("");
            cb_dueño.setSelectedIndex(0);
            j_datelife.setDate(new Date());
            j_datefc.setDate(new Date());
            tf_instruc.setText("");
        }
    }//GEN-LAST:event_CrearMouseClicked

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_loginActionPerformed

    private void rb_madreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_madreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_madreActionPerformed

    private void Registrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Registrar2MouseClicked
        // TODO add your handling code here:
        //Antes pedia las cosas especificas de cada tipo pero nose como ni porque se borro
        boolean val = false;
        for (int i = 0; i < users.size(); i++) {
            if (users.get(i).getUser().equals(tf_usern.getText())) {
                JOptionPane.showMessageDialog(this, "El usuario ya existe");
                val = false;
                break;
            } else {
                val = true;
            }
        }
        boolean val2 = false;
        if (val == true) {
            String nombre = tf_nombre.getText();
            String user = tf_usern.getText();
            String sexo = tf_sex.getText();
            String contra = tf_contraa.getText();
            int id = Integer.parseInt(tf_ident.getText());
            String est = tf_ec.getText();
            int edad = Integer.parseInt(tf_age.getText());
            String rol = "";
            if (rb_madre.isSelected()) {
                for (int i = 0; i < users.size(); i++) {
                    if (users.get(i) instanceof Madre) {
                        JOptionPane.showMessageDialog(this, "Ya existe una madre");
                        val2 = false;
                        break;
                    } else {
                        val2 = true;
                    }
                }
                if (val2 == true) {
                    rol = "Madre";
                    users.add(new Madre(nombre, edad, id, sexo, est, user, contra, rol));
                    Register.setVisible(false);
                    this.setVisible(true);
                }
            } else if (rb_padre.isSelected()) {
                for (int i = 0; i < users.size(); i++) {
                    if (users.get(i) instanceof Padre) {
                        JOptionPane.showMessageDialog(this, "Ya existe un padre");
                        val2 = false;
                        break;
                    } else {
                        val2 = true;
                    }
                }
                if (val2 == true) {
                    users.add(new Padre(nombre, edad, id, sexo, est, user, contra, rol));
                    Register.setVisible(false);
                    this.setVisible(true);
                }
            } else if (rb_hermano.isSelected()) {
                for (int i = 0; i < users.size(); i++) {
                    if (users.get(i) instanceof Hermano) {
                        JOptionPane.showMessageDialog(this, "Ya existe un hermano");
                        val2 = false;
                        break;
                    } else {
                        val2 = true;
                    }
                }
                if (val2 == true) {
                    users.add(new Hermano(nombre, edad, id, sexo, est, user, contra, rol));
                    Register.setVisible(false);
                    this.setVisible(true);
                }
            } else if (rb_hermana.isSelected()) {
                int cont = 0;
                for (int i = 0; i < users.size(); i++) {
                    if (users.get(i) instanceof Hermana) {
                        cont++;
                    }
                }
                if (cont == 4) {
                    JOptionPane.showMessageDialog(this, "Ya estan las 4 hermanas");
                    val2 = false;
                } else {
                    val2 = true;
                }
                if (val2 == true) {
                    users.add(new Hermana(nombre, edad, id, sexo, est, user, contra, rol));
                    Register.setVisible(false);
                    this.setVisible(true);
                }
            } else if (rb_esposo.isSelected()) {
                for (int i = 0; i < users.size(); i++) {
                    if (users.get(i) instanceof Esposo) {
                        JOptionPane.showMessageDialog(this, "Ya existe un esposo");
                        val2 = false;
                        break;
                    } else {
                        val2 = true;
                    }
                }
                if (val2 == true) {
                    users.add(new Esposo(nombre, edad, id, sexo, est, user, contra, rol));
                    Register.setVisible(false);
                    this.setVisible(true);
                }
            } else {
                users.add(new Personal(nombre, edad, id, sexo, est, user, contra, rol));
                Register.setVisible(false);
                this.setVisible(true);
            }
            DefaultComboBoxModel model = (DefaultComboBoxModel) cb_dueño.getModel();
            model.addElement(users.get(users.size() - 1));
            cb_dueño.setModel(model);
            DefaultComboBoxModel mode = (DefaultComboBoxModel) cb_elim.getModel();
            mode.addElement(users.get(users.size() - 1));
            cb_elim.setModel(mode);
            DefaultComboBoxModel mod = (DefaultComboBoxModel) cb_list.getModel();
            mod.addElement(users.get(users.size() - 1));
            cb_list.setModel(mod);
            DefaultComboBoxModel m = (DefaultComboBoxModel) cb_mensaje.getModel();
            m.addElement(users.get(users.size() - 1));
            cb_mensaje.setModel(m);
            
        }

    }//GEN-LAST:event_Registrar2MouseClicked

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
        // TODO add your handling code here:
        Personas destinatario = (Personas) cb_mensaje.getSelectedItem();
        String msg = ta_mensaje.getText();
        ((Familiares) (destinatario)).getMsgs().add(new Mensajes(destinatario, msg));
        ta_mensaje.setText("");
    }//GEN-LAST:event_sendMouseClicked

    private void seeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < ((Familiares) (actual)).getMsgs().size(); i++) {
            JOptionPane.showMessageDialog(this, "De: " + actual.getNombre() + "\n" + ((Familiares) (actual)).getMsgs().get(i).toString());
        }

    }//GEN-LAST:event_seeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    ArrayList<Personas> users = new ArrayList();
    Personas actual;
    ArrayList<Mensajes> msgs;
    Familiares Kim = new Familiares();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Acciones;
    private javax.swing.JButton Crear;
    private javax.swing.ButtonGroup Familia;
    private javax.swing.JFrame Register;
    private javax.swing.JButton Registrar2;
    private javax.swing.ButtonGroup Rol;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.ButtonGroup Tipo;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_register;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_dueño;
    private javax.swing.JComboBox<String> cb_elim;
    private javax.swing.JComboBox<String> cb_list;
    private javax.swing.JComboBox<String> cb_mensaje;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private com.toedter.calendar.JDateChooser j_datefc;
    private com.toedter.calendar.JDateChooser j_datelife;
    private javax.swing.JRadioButton rb_cocina;
    private javax.swing.JRadioButton rb_esposo;
    private javax.swing.JRadioButton rb_h;
    private javax.swing.JRadioButton rb_habitacion;
    private javax.swing.JRadioButton rb_hermana;
    private javax.swing.JRadioButton rb_hermano;
    private javax.swing.JRadioButton rb_madre;
    private javax.swing.JRadioButton rb_padre;
    private javax.swing.JRadioButton rb_personal;
    private javax.swing.JRadioButton rb_r;
    private javax.swing.JRadioButton rb_sala;
    private javax.swing.JRadioButton rb_z;
    private javax.swing.JButton see;
    private javax.swing.JButton send;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTextField tf_age;
    private javax.swing.JTextField tf_calidad;
    private javax.swing.JTextField tf_confort;
    private javax.swing.JTextField tf_contraa;
    private javax.swing.JTextField tf_descript;
    private javax.swing.JTextField tf_ec;
    private javax.swing.JTextField tf_ident;
    private javax.swing.JTextField tf_instruc;
    private javax.swing.JTextField tf_logcontra;
    private javax.swing.JTextField tf_logname;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_material;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_pelab;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_sex;
    private javax.swing.JTextField tf_suela;
    private javax.swing.JTextField tf_talla;
    private javax.swing.JTextField tf_tamaño;
    private javax.swing.JTextField tf_usern;
    private javax.swing.JPanel tp_create;
    private javax.swing.JPanel tp_elim;
    private javax.swing.JPanel tp_list;
    private javax.swing.JPanel tp_mensaj;
    private javax.swing.JPanel tp_mod;
    // End of variables declaration//GEN-END:variables
}
